# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core 3.1 Preview'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
    includePreviewVersions: true
- task: DotNetCoreCLI@2
  displayName: 'Build Birds App'
  inputs:
    command: 'build'
    projects: '$(System.DefaultWorkingDirectory)/birds_blazor/birds_blazor.csproj'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/birds_blazor'
    artifact: 'birds_blazor_app'
    publishLocation: 'pipeline'


